import Chat from "@/components/pages/chat/Chat";

export const metadata = {
    title: "Three dots | Kết nối bạn bè",
    description: "Generated by create next app",
};
export default function ChatLayout({ children }) {
    return (
        <>
            <Chat>{children}</Chat>
        </>
    );
}
