import Chat from "@/components/pages/chat/Chat";

export const metadata = {
    title: "Three dots | Kết nối bạn bè",
    description: "Generated by create next app",
};
export default function ChatLayout({ children }) {
    return (
        <div className="w-full flex justify-center ">
            <div className="max-w-[1230px] w-full">
                <Chat>{children}</Chat>
            </div>
        </div>
    );
}
