import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header/Header";
import AuthProvider from "@/context/AuthProvider";
import Navigate from "@/components/header/Navigate";
import ProgressBar from "@/components/progress/ProgressBar";

import { BlogProvider } from "@/context/BlogContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Three dots",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
                <body className={inter.className}>
                    <ProgressBar>
                        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                            <AuthProvider>
                                <Toaster />
                                <Header />
                                <BlogProvider>{children}</BlogProvider>
                                <div className="backdrop-blur-md bg-[hsl(var(--background)/87%)] sticky w-full flex justify-center bottom-0 z-50 left-0 sm:hidden">
                                    <Navigate />
                                </div>
                            </AuthProvider>
                        </ThemeProvider>
                    </ProgressBar>
                </body>
            </html>
        </>
    );
}
